version: "3.8"

services:
  web:
    build: .
    command: ["bash", "/app/start.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/edis_lite
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=edis_lite
    ports:
      - "5433:5432"

volumes:
  postgres_data: 